INSERT INTO category (version,description) VALUES (0,'American');
INSERT INTO category (version,description) VALUES (0,'Italian');
INSERT INTO category (version,description) VALUES (0,'Mexican');
INSERT INTO category (version,description) VALUES (0,'Fast Food');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Teaspoon');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Tablespoon');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Cup');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Pinch');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Ounce');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Each');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Dash');
INSERT INTO unit_of_measure (version,description) VALUES (0,'Pint');
